-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 23, 2024 at 11:33 PM
-- Server version: 5.7.23-23
-- PHP Version: 8.1.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `omkriuhp_new`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_items`
--

CREATE TABLE `tbl_items` (
  `item_id` int(11) NOT NULL,
  `o_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `o_desc` text COLLATE utf8_unicode_ci,
  `o_image` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `o_image1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `o_image2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `o_image3` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `o_image4` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_cat` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `tbl_items`
--

INSERT INTO `tbl_items` (`item_id`, `o_name`, `o_desc`, `o_image`, `o_image1`, `o_image2`, `o_image3`, `o_image4`, `item_cat`, `price`) VALUES
(1, '8-Sheet Cross-Cut Paper Shredder', 'Compact paper shredder with thermal protection and auto start/stop from Amazon Basics.', 'paper_shredder_1.png', 'paper_shredder_2.jpg', 'paper_shredder_3.jpg', 'paper_shredder_4.jpg', 'paper_shredder_5.jpg', 'cheap_electronics', 40),
(2, 'Fire TV Stick Lite with Alexa Voice Remote Lite', 'Affordable streaming media player with HD streaming and Alexa Voice Remote Lite from Amazon.', 'firetv_stick_lite_1.png', 'firetv_stick_lite_2.jpg', 'firetv_stick_lite_3.jpg', 'firetv_stick_lite_4.jpg', 'firetv_stick_lite_5.jpg', 'cheap_electronics', 25),
(3, 'Anker Soundcore Bluetooth Speaker', 'Portable Bluetooth speaker with 24-hour playtime and powerful stereo sound from Anker.', 'anker_soundcore_speaker_1.png', 'anker_soundcore_speaker_2.jpg', 'anker_soundcore_speaker_3.jpg', 'anker_soundcore_speaker_4.jpg', 'anker_soundcore_speaker_5.jpg', 'cheap_electronics', 30),
(4, 'Panasonic ErgoFit In-Ear Earbud Headphones', 'Comfortable in-ear headphones with wide frequency response and ergonomic fit from Panasonic.', 'panasonic_ergofit_earbuds_1.png', 'panasonic_ergofit_earbuds_2.jpg', 'panasonic_ergofit_earbuds_3.jpg', 'panasonic_ergofit_earbuds_4.jpg', 'panasonic_ergofit_earbuds_5.jpg', 'cheap_electronics', 13),
(5, 'VTech DECT 6.0 Cordless Phone', 'Digital cordless phone with caller ID and handset speakerphone from VTech.', 'vtech_dect_cordlessphone_1.png', 'vtech_dect_cordlessphone_2.jpg', NULL, NULL, NULL, 'cheap_electronics', 30),
(6, 'Neutrogena Hydro Boost Water Gel', 'Lightweight water gel moisturizer with hyaluronic acid for smooth and supple skin from Neutrogena.', 'neutrogena_hydroboost_gel_1.png', 'neutrogena_hydroboost_gel_2.jpg', 'neutrogena_hydroboost_gel_3.jpg', NULL, NULL, 'cheap_beauty', 17),
(7, 'Revlon One-Step Hair Dryer and Volumizer', '2-in-1 hair dryer and volumizer brush for frizz-free volume and shine from Revlon.', 'revlon_hairdryer_volumizer_1.png', 'revlon_hairdryer_volumizer_2.jpg', 'revlon_hairdryer_volumizer_3.jpg', 'revlon_hairdryer_volumizer_4.jpg', 'revlon_hairdryer_volumizer_5.jpg', 'cheap_beauty', 42),
(8, 'CeraVe Hydrating Facial Cleanser', 'Gentle cleanser with ceramides and hyaluronic acid for effective hydration from CeraVe.', 'cerave_hydrating_cleanser_1.png', 'cerave_hydrating_cleanser_2.jpg', 'cerave_hydrating_cleanser_3.jpg', 'cerave_hydrating_cleanser_4.jpg', NULL, 'cheap_beauty', 15),
(9, 'Oral-B Pro 1000 Electric Toothbrush', 'Rechargeable electric toothbrush with CrossAction brush head from Oral-B.', 'oralb_pro1000_toothbrush_1.png', 'oralb_pro1000_toothbrush_2.jpg', 'oralb_pro1000_toothbrush_3.jpg', 'oralb_pro1000_toothbrush_4.jpg', NULL, 'cheap_beauty', 40),
(10, 'Olay Regenerist Micro-Sculpting Cream', 'Anti-aging moisturizer with hyaluronic acid, amino-peptides, and vitamin B3 from Olay.', 'olay_regenerist_cream_1.png', 'olay_regenerist_cream_2.jpg', 'olay_regenerist_cream_3.jpg', 'olay_regenerist_cream_4.jpg', 'olay_regenerist_cream_5.jpg', 'cheap_beauty', 25),
(11, 'Becoming by Michelle Obama', 'Memoir by Michelle Obama reflecting on her experiences, values, and journey.', 'becoming_michelleobama_book_1.jpg', NULL, '', '', '', 'cheap_books', 12),
(12, 'The Subtle Art of Not Giving a F*ck by Mark Manson', 'Self-help book offering unconventional wisdom about living a good life by Mark Manson.', 'subtle_art_manson_book_1.jpg', NULL, '', '', '', 'cheap_books', 12),
(13, '1984 by George Orwell', 'Classic dystopian novel depicting a totalitarian future society by George Orwell.', '1984_georgeorwell_book_1.png', '1984_georgeorwell_book_2.jpg', '', '', '', 'cheap_books', 8),
(14, 'Harry Potter and the Sorcerer\'s Stone by J.K. Rowling', 'First book in the Harry Potter series about a young wizard\'s journey by J.K. Rowling.', 'harrypotter_sorcerersstone_book_1.jpg', NULL, '', '', '', 'cheap_books', 9),
(15, 'Educated by Tara Westover', 'Memoir recounting a woman\'s quest for knowledge and education against all odds by Tara Westover.', 'educated_tarawestover_book_1.jpg', NULL, '', '', '', 'cheap_books', 11),
(16, 'Levi\'s Men\'s 505 Regular Fit Jeans', 'Classic fit jeans with straight leg and zip fly closure from Levi\'s.', 'levis_505_jeans_1.png', 'levis_505_jeans_2.jpg', 'levis_505_jeans_3.jpg', 'levis_505_jeans_4.jpg', 'levis_505_jeans_5.jpg', 'cheap_fashion', 40),
(17, 'Adidas Originals Men\'s Trefoil T-Shirt', 'Cotton jersey t-shirt featuring the iconic Trefoil logo from Adidas Originals.', 'adidas_trefoil_tshirt_1.png', 'adidas_trefoil_tshirt_2.jpg', '', NULL, NULL, 'cheap_fashion', 25),
(18, 'Hanes Men\'s Pullover EcoSmart Hoodie', 'Comfortable fleece hoodie made with recycled materials from Hanes.', 'hanes_ecosmart_hoodie_1.png', NULL, NULL, NULL, NULL, 'cheap_fashion', 19),
(19, 'Champion Men\'s Classic Jersey Script T-Shirt', 'Cotton jersey t-shirt with embroidered Champion logo script.', 'champion_script_tshirt_1.png', 'champion_script_tshirt_2.jpg', 'champion_script_tshirt_3.jpg', NULL, NULL, 'cheap_fashion', 15),
(20, 'Timberland Men\'s White Ledge Mid Waterproof Ankle Boot', 'Mid-rise waterproof leather hiking boot with padded collar and rubber sole from Timberland.', 'timberland_whiteledge_boot_1.png', 'timberland_whiteledge_boot_2.jpg', 'timberland_whiteledge_boot_3.jpg', 'timberland_whiteledge_boot_4.jpg', 'timberland_whiteledge_boot_5.jpg', 'cheap_fashion', 80),
(21, 'Hamilton Beach Electric Kettle', 'Stainless steel electric kettle with rapid-boil technology and automatic shutoff from Hamilton Beach.', 'hamiltonbeach_electrickettle_1.png', 'hamiltonbeach_electrickettle_2.jpg', 'hamiltonbeach_electrickettle_3.jpg', 'hamiltonbeach_electrickettle_4.jpg', 'hamiltonbeach_electrickettle_5.jpg', 'cheap_appliances', 20),
(22, 'BLACK+DECKER 4-Slice Toaster Oven', 'Compact toaster oven with bake, broil, and toast functions from BLACK+DECKER.', 'blackdecker_toasteroven_1.png', 'blackdecker_toasteroven_2.jpg', 'blackdecker_toasteroven_3.jpg', 'blackdecker_toasteroven_4.jpg', NULL, 'cheap_appliances', 40),
(23, 'Dash Mini Waffle Maker', 'Mini waffle maker with nonstick surface for individual waffles from Dash.', 'dash_mini_wafflemaker_1.png', 'dash_mini_wafflemaker_2.jpg', 'dash_mini_wafflemaker_3.jpg', 'dash_mini_wafflemaker_4.jpg', 'dash_mini_wafflemaker_5.jpg', 'cheap_appliances', 10),
(24, 'Dirt Devil Simpli-Stik Vacuum Cleaner', 'Lightweight stick vacuum cleaner with detachable handheld vacuum from Dirt Devil.', 'dirtdevil_simplistik_vacuum_1.png', 'dirtdevil_simplistik_vacuum_2.jpg', 'dirtdevil_simplistik_vacuum_3.jpg', 'dirtdevil_simplistik_vacuum_4.jpg', 'dirtdevil_simplistik_vacuum_5.jpg', 'cheap_appliances', 25),
(25, 'Compact Refrigerator', 'Mini refrigerator with adjustable thermostat and reversible door from RCA.', 'rca_compact_refrigerator_1.png', 'rca_compact_refrigerator_2.jpg', 'rca_compact_refrigerator_3.jpg', 'rca_compact_refrigerator_4.jpg', 'rca_compact_refrigerator_5.jpg', 'cheap_appliances', 140),
(26, 'Franklin Sports Mini Basketball Hoop', 'Indoor basketball hoop set with foam basketball from Franklin Sports.', 'franklin_sports_minihoop_1.png', 'franklin_sports_minihoop_2.jpg', 'franklin_sports_minihoop_3.jpg', NULL, NULL, 'cheap_sports', 20),
(27, 'Intex Classic Downy Airbed', 'Durable inflatable airbed with waterproof flocked top and 2-in-1 valve from Intex.', 'intex_downy_airbed_1.png', 'intex_downy_airbed_2.jpg', 'intex_downy_airbed_3.jpg', 'intex_downy_airbed_4.jpg', NULL, 'cheap_sports', 10),
(28, 'Wilson NFL MVP Football', 'Official size football with tackified composite leather cover from Wilson.', 'wilson_nfl_football_1.png', NULL, NULL, NULL, NULL, 'cheap_sports', 15),
(29, 'Coleman Sundome Tent', 'Lightweight camping tent with WeatherTec system and ventilation from Coleman.', 'coleman_sundome_tent_1.png', 'coleman_sundome_tent_2.jpg', 'coleman_sundome_tent_3.jpg', 'coleman_sundome_tent_4.jpg', 'coleman_sundome_tent_5.jpg', 'cheap_sports', 50),
(30, 'Neoprene Dumbbell Set', 'Neoprene-coated dumbbell set with rack for resistance training from Amazon Basics.', 'dumbbell_set_1.png', 'dumbbell_set_2.jpg', 'dumbbell_set_3.jpg', 'dumbbell_set_4.jpg', NULL, 'cheap_sports', 45),
(31, 'Sony ZX Series Wired On-Ear Headphones', 'Lightweight and comfortable wired headphones with swivel design from Sony.', 'sony_zx_headphones_1.png', 'sony_zx_headphones_2.jpg', 'sony_zx_headphones_3.jpg', 'sony_zx_headphones_4.jpg', NULL, 'cheap_electronics', 15),
(32, 'TP-Link N300 WiFi Range Extender', 'Compact WiFi extender with external antennas for better coverage from TP-Link.', 'tplink_wifi_extender_1.png', 'tplink_wifi_extender_2.jpg', 'tplink_wifi_extender_3.jpg', 'tplink_wifi_extender_4.jpg', 'tplink_wifi_extender_5.jpg', 'cheap_electronics', 20),
(33, 'SanDisk Ultra 64GB microSDXC Memory Card', 'High-performance microSDXC card for Android devices and cameras from SanDisk.', 'sandisk_microsdxc_card_1.png', 'sandisk_microsdxc_card_2.jpg', 'sandisk_microsdxc_card_3.jpg', 'sandisk_microsdxc_card_4.jpg', 'sandisk_microsdxc_card_5.jpg', 'cheap_electronics', 12),
(34, 'Logitech M510 Wireless Computer Mouse', 'Ergonomic wireless mouse with side grips and programmable buttons from Logitech.', 'logitech_m510_mouse_1.png', 'logitech_m510_mouse_2.jpg', 'logitech_m510_mouse_3.jpg', NULL, NULL, 'cheap_electronics', 20),
(35, 'Energizer LED Tactical Flashlight', 'Durable LED flashlight with multiple light modes and water-resistant design from Energizer.', 'energizer_tactical_flashlight_1.png', 'energizer_tactical_flashlight_2.jpg', 'energizer_tactical_flashlight_3.jpg', 'energizer_tactical_flashlight_4.jpg', 'energizer_tactical_flashlight_5.jpg', 'cheap_electronics', 10),
(36, 'Maybelline New York Great Lash Mascara', 'Iconic mascara with a lash-building brush for full lashes from Maybelline New York.', 'maybelline_greatlash_mascara_1.png', 'maybelline_greatlash_mascara_2.jpg', 'maybelline_greatlash_mascara_3.jpg', 'maybelline_greatlash_mascara_4.jpg', 'maybelline_greatlash_mascara_5.jpg', 'cheap_beauty', 4),
(37, 'Crest 3D White Whitestrips', 'Teeth whitening strips with advanced seal technology from Crest 3D White.', 'crest_whitestrips_1.png', 'crest_whitestrips_2.jpg', 'crest_whitestrips_3.jpg', NULL, NULL, 'cheap_beauty', 35),
(38, 'Neutrogena Oil-Free Facial Moisturizer', 'Lightweight oil-free moisturizer with SPF 35 sunscreen from Neutrogena.', 'neutrogena_oilfree_moisturizer_1.png', 'neutrogena_oilfree_moisturizer_2.jpg', 'neutrogena_oilfree_moisturizer_3.jpg', 'neutrogena_oilfree_moisturizer_4.jpg', NULL, 'cheap_beauty', 10),
(39, 'Conair Double Ceramic Curling Iron', 'Ceramic curling iron with 1-inch barrel for smooth and shiny curls from Conair.', 'conair_ceramic_curlingiron_1.png', 'conair_ceramic_curlingiron_2.jpg', 'conair_ceramic_curlingiron_3.jpg', 'conair_ceramic_curlingiron_4.jpg', 'conair_ceramic_curlingiron_5.jpg', 'cheap_beauty', 12),
(40, 'Burt\'s Bees 100% Natural Lip Balm', 'Moisturizing lip balm made with beeswax and peppermint from Burt\'s Bees.', 'burtsbees_lipbalm_1.png', 'burtsbees_lipbalm_2.jpg', 'burtsbees_lipbalm_3.jpg', 'burtsbees_lipbalm_4.jpg', 'burtsbees_lipbalm_5.jpg', 'cheap_beauty', 3),
(41, 'The Alchemist by Paulo Coelho', 'Inspirational novel about following dreams and destiny by Paulo Coelho.', 'alchemist_paulocoelho_book_1.jpg', NULL, '', '', '', 'cheap_books', 7),
(42, 'Atomic Habits by James Clear', 'Practical guide to building good habits and breaking bad ones by James Clear.', 'atomic_habits_jamesclear_book_1.jpg', NULL, '', '', '', 'cheap_books', 12),
(43, 'The Silent Patient by Alex Michaelides', 'Psychological thriller about a woman\'s shocking act of violence by Alex Michaelides.', 'silent_patient_alexmichaelides_book_1.jpg', '', '', '', '', 'cheap_books', 11),
(44, 'To Kill a Mockingbird by Harper Lee', 'Classic novel addressing racial injustice and moral growth by Harper Lee.', 'tokillamockingbird_harperlee_book_1.jpg', NULL, '', '', '', 'cheap_books', 9),
(45, 'Educated by Tara Westover', 'Memoir recounting a woman\'s quest for knowledge and education against all odds by Tara Westover.', 'educated_tarawestover_book_2.jpg', NULL, '', '', '', 'cheap_books', 11),
(46, 'Wrangler Authentics Men\'s Classic 5-Pocket Regular Fit Jean', 'Classic fit jeans with five-pocket styling and durable denim from Wrangler Authentics.', 'wrangler_authentics_jeans_1.png', 'wrangler_authentics_jeans_2.jpg', 'wrangler_authentics_jeans_3.jpg', 'wrangler_authentics_jeans_4.jpg', 'wrangler_authentics_jeans_5.jpg', 'cheap_fashion', 24),
(47, 'Hanes Men\'s ComfortSoft Short Sleeve T-Shirt', 'Cotton jersey t-shirt with lay flat collar from Hanes ComfortSoft.', 'hanes_comfortsoft_tshirt_1.png', 'hanes_comfortsoft_tshirt_2.jpg', 'hanes_comfortsoft_tshirt_3.jpg', 'hanes_comfortsoft_tshirt_4.jpg', 'hanes_comfortsoft_tshirt_5.jpg', 'cheap_fashion', 5),
(48, 'Levi\'s Men\'s 511 Slim Fit Jeans', 'Slim fit jeans with stretch denim and zipper closure from Levi\'s.', 'levis_511_jeans_1.png', 'levis_511_jeans_2.jpg', 'levis_511_jeans_3.jpg', 'levis_511_jeans_4.jpg', 'levis_511_jeans_5.jpg', 'cheap_fashion', 42),
(49, 'Adidas Men\'s Essentials 3-Stripes Hoodie', 'Fleece hoodie with 3-Stripes design and kangaroo pocket from Adidas Essentials.', 'adidas_3stripes_hoodie_1.png', 'adidas_3stripes_hoodie_2.jpg', 'adidas_3stripes_hoodie_3.jpg', 'adidas_3stripes_hoodie_4.jpg', 'adidas_3stripes_hoodie_5.jpg', 'cheap_fashion', 37),
(50, 'Champion Men\'s Classic Jersey Script T-Shirt', 'Cotton jersey t-shirt with embroidered Champion logo script.', 'champion_script_tshirt_3.png', 'champion_script_tshirt_4.jpg', NULL, NULL, NULL, 'cheap_fashion', 15),
(51, 'Electric Can Opener', 'Electric can opener with stainless steel blade and automatic shut-off from Amazon Basics.', 'canopener_1.png', 'canopener_2.jpg', 'canopener_3.jpg', 'canopener_4.jpg', 'canopener_5.jpg', 'cheap_appliances', 18),
(52, 'Oster 2-Slice Toaster', 'Two-slice toaster with auto-adjusting bread guides and removable crumb tray from Oster.', 'oster_2slice_toaster_1.png', 'oster_2slice_toaster_2.jpg', 'oster_2slice_toaster_3.jpg', NULL, NULL, 'cheap_appliances', 20),
(53, 'Hamilton Beach Personal Blender', 'Compact blender with travel lid for shakes and smoothies from Hamilton Beach.', 'hamiltonbeach_personalblender_1.png', 'hamiltonbeach_personalblender_2.jpg', 'hamiltonbeach_personalblender_3.jpg', 'hamiltonbeach_personalblender_4.jpg', 'hamiltonbeach_personalblender_5.jpg', 'cheap_appliances', 16),
(54, 'Proctor Silex 1.5-Quart Slow Cooker', 'Small slow cooker with removable crock for easy cleaning from Proctor Silex.', 'proctorsilex_slowcooker_1.png', 'proctorsilex_slowcooker_2.jpg', 'proctorsilex_slowcooker_3.jpg', 'proctorsilex_slowcooker_4.jpg', 'proctorsilex_slowcooker_5.jpg', 'cheap_appliances', 16),
(55, 'Sunbeam Steam Master Iron', 'Steam iron with retractable cord and anti-drip system from Sunbeam.', 'sunbeam_steammaster_iron_1.png', 'sunbeam_steammaster_iron_2.jpg', 'sunbeam_steammaster_iron_3.jpg', 'sunbeam_steammaster_iron_4.jpg', 'sunbeam_steammaster_iron_5.jpg', 'cheap_appliances', 30),
(56, 'Spalding NBA Street Basketball', 'Outdoor basketball with durable rubber cover and deep channel design from Spalding.', 'spalding_street_basketball_1.png', 'spalding_street_basketball_2.jpg', 'spalding_street_basketball_3.jpg', 'spalding_street_basketball_4.jpg', 'spalding_street_basketball_5.jpg', 'cheap_sports', 15),
(57, 'Exercise Mat with EVA Foam Interlocking Tiles', 'Interlocking exercise mat set with foam tiles for cushioning from Amazon Basics.', 'exercisemat_1.png', 'exercisemat_2.jpg', 'exercisemat_3.jpg', 'exercisemat_4.jpg', 'exercisemat_5.jpg', 'cheap_sports', 27),
(58, 'Gaiam Essentials Yoga Block', 'High-density foam yoga block for stretching and balance from Gaiam Essentials.', 'gaiam_essentials_yogablock_1.png', 'gaiam_essentials_yogablock_2.jpg', 'gaiam_essentials_yogablock_3.jpg', 'gaiam_essentials_yogablock_4.jpg', 'gaiam_essentials_yogablock_5.jpg', 'cheap_sports', 11),
(59, 'Coleman 16-Can Soft Cooler', 'Soft cooler with adjustable shoulder strap and antimicrobial liner from Coleman.', 'coleman_softcooler_1.png', 'coleman_softcooler_2.jpg', 'coleman_softcooler_3.jpg', 'coleman_softcooler_4.jpg', 'coleman_softcooler_5.jpg', 'cheap_sports', 20),
(60, 'Wilson US Open Junior Tennis Racquet', 'Junior tennis racquet with lightweight frame and cushioned grip from Wilson.', 'wilson_usopen_juniorracquet_1.png', 'wilson_usopen_juniorracquet_2.jpg', '', NULL, NULL, 'cheap_sports', 23),
(61, 'Wireless Computer Mouse', 'Wireless optical mouse with nano receiver and 3 adjustable DPI levels from Amazon Basics.', 'wireless_mouse_1.png', 'wireless_mouse_2.jpg', 'wireless_mouse_3.jpg', 'wireless_mouse_4.jpg', 'wireless_mouse_5.jpg', 'cheap_electronics', 12),
(62, 'Anker PowerCore 10000 Portable Charger', 'Compact portable charger with 10000mAh capacity and PowerIQ technology from Anker.', 'anker_powercore_portablecharger_1.png', 'anker_powercore_portablecharger_2.jpg', 'anker_powercore_portablecharger_3.jpg', 'anker_powercore_portablecharger_4.jpg', 'anker_powercore_portablecharger_5.jpg', 'cheap_electronics', 26),
(63, 'JBL Tune 115TWS True Wireless Earbuds', 'True wireless earbuds with JBL Pure Bass sound and dual connect technology.', 'jbl_tune_115tws_earbuds_1.png', 'jbl_tune_115tws_earbuds_2.jpg', 'jbl_tune_115tws_earbuds_3.jpg', 'jbl_tune_115tws_earbuds_4.jpg', 'jbl_tune_115tws_earbuds_5.jpg', 'cheap_electronics', 40),
(64, 'Samsung 32GB BAR Plus USB 3.1 Flash Drive', 'Metal casing USB 3.1 flash drive with 200MB/s read speed from Samsung.', 'samsung_barplus_flashdrive_1.png', 'samsung_barplus_flashdrive_2.jpg', 'samsung_barplus_flashdrive_3.jpg', 'samsung_barplus_flashdrive_4.jpg', 'samsung_barplus_flashdrive_5.jpg', 'cheap_electronics', 10),
(65, 'Fire TV Stick Lite with Alexa Voice Remote', 'HD streaming device with Alexa Voice Remote Lite for access to movies, TV shows, and apps.', 'firetv_stick_lite_1.png', 'firetv_stick_lite_2.jpg', 'firetv_stick_lite_3.jpg', 'firetv_stick_lite_4.jpg', 'firetv_stick_lite_5.jpg', 'cheap_electronics', 25),
(66, 'Revlon One-Step Hair Dryer and Volumizer', 'Hair dryer and volumizer brush for smooth and shiny hair styling from Revlon.', 'revlon_hairdryer_volumizer_1.png', 'revlon_hairdryer_volumizer_2.jpg', 'revlon_hairdryer_volumizer_3.jpg', 'revlon_hairdryer_volumizer_4.jpg', 'revlon_hairdryer_volumizer_5.jpg', 'cheap_beauty', 42),
(67, 'Cetaphil Gentle Skin Cleanser', 'Gentle hydrating cleanser for all skin types from Cetaphil.', 'cetaphil_cleanser_1.png', 'cetaphil_cleanser_2.jpg', NULL, '', '', 'cheap_beauty', 10),
(68, 'CeraVe Moisturizing Cream', 'Rich moisturizing cream with hyaluronic acid and ceramides from CeraVe.', 'cerave_moisturizing_cream_1.png', 'cerave_moisturizing_cream_2.jpg', 'cerave_moisturizing_cream_3.jpg', 'cerave_moisturizing_cream_4.jpg', 'cerave_moisturizing_cream_5.jpg', 'cheap_beauty', 14),
(69, 'Olay Regenerist Micro-Sculpting Cream', 'Anti-aging moisturizer with amino-peptide complex II and hyaluronic acid from Olay.', 'olay_regenerist_cream_6.png', 'olay_regenerist_cream_7.jpg', 'olay_regenerist_cream_8.jpg', 'olay_regenerist_cream_9.jpg', 'olay_regenerist_cream_10.jpg', 'cheap_beauty', 22),
(70, 'Gillette Fusion5 Men\'s Razor', 'Men\'s razor with 5 anti-friction blades and lubrication strip from Gillette Fusion5.', 'gillette_fusion5_razor_1.png', 'gillette_fusion5_razor_2.jpg', 'gillette_fusion5_razor_3.jpg', 'gillette_fusion5_razor_4.jpg', 'gillette_fusion5_razor_5.jpg', 'cheap_beauty', 10),
(71, 'Becoming by Michelle Obama', 'Memoir by former First Lady Michelle Obama on her journey from the South Side of Chicago to the White House.', 'becoming_michelleobama_book_2.jpg', NULL, '', '', '', 'cheap_books', 11),
(72, 'The Subtle Art of Not Giving a F*ck by Mark Manson', 'Counterintuitive approach to living a good life by focusing on what truly matters by Mark Manson.', 'subtle_art_markmanson_book_2.jpg', NULL, '', '', '', 'cheap_books', 14),
(73, 'The Four Agreements by Don Miguel Ruiz', 'Guide to personal freedom and spiritual growth based on ancient Toltec wisdom by Don Miguel Ruiz.', 'four_agreements_donmiguelruiz_book_1.jpg', NULL, '', '', '', 'cheap_books', 6),
(74, 'The Power of Now by Eckhart Tolle', 'Guide to spiritual enlightenment and living in the present moment by Eckhart Tolle.', 'power_of_now_eckharttolle_book_1.jpg', NULL, '', '', '', 'cheap_books', 9),
(75, 'Daring Greatly by Brené Brown', 'Research-based approach to vulnerability, courage, and worthiness by Brené Brown.', 'daring_greatly_brenebrown_book_1.jpg', NULL, '', '', '', 'cheap_books', 11),
(76, 'Columbia Women\'s Benton Springs Full Zip Fleece Jacket', 'Soft fleece jacket with zippered pockets and stand-up collar from Columbia.', 'columbia_bentonsprings_jacket_1.png', 'columbia_bentonsprings_jacket_2.jpg', 'columbia_bentonsprings_jacket_3.jpg', 'columbia_bentonsprings_jacket_4.jpg', NULL, 'cheap_fashion', 25),
(77, 'Levi\'s Women\'s 721 High Rise Skinny Jeans', 'High-rise skinny jeans with stretch denim and slim fit from Levi\'s.', 'levis_721_jeans_1.png', 'levis_721_jeans_2.jpg', 'levis_721_jeans_3.jpg', 'levis_721_jeans_4.jpg', 'levis_721_jeans_5.jpg', 'cheap_fashion', 50),
(78, 'Under Armour Men\'s Tech 2.0 Short Sleeve T-Shirt', 'Quick-drying athletic t-shirt with UA Tech fabric and anti-odor technology from Under Armour.', 'underarmour_tech_tshirt_1.png', NULL, '', '', NULL, 'cheap_fashion', 25),
(79, 'Calvin Klein Men\'s Cotton Classics Multipack Boxer Briefs', 'Multipack boxer briefs made from soft and breathable cotton from Calvin Klein.', 'calvinklein_boxerbriefs_1.png', 'calvinklein_boxerbriefs_2.jpg', 'calvinklein_boxerbriefs_3.jpg', 'calvinklein_boxerbriefs_4.jpg', NULL, 'cheap_fashion', 29),
(80, 'Fossil Men\'s Neutra Chronograph Stainless Steel Watch', 'Stainless steel chronograph watch with quartz movement and date window from Fossil.', 'fossil_neutra_watch_1.png', 'fossil_neutra_watch_2.jpg', 'fossil_neutra_watch_3.jpg', 'fossil_neutra_watch_4.jpg', 'fossil_neutra_watch_5.jpg', 'cheap_fashion', 90),
(81, 'BLACK+DECKER Dustbuster Handheld Vacuum', 'Cordless handheld vacuum cleaner with rotating nozzle and washable filter from BLACK+DECKER.', 'blackdecker_dustbuster_1.png', 'blackdecker_dustbuster_2.jpg', 'blackdecker_dustbuster_3.jpg', 'blackdecker_dustbuster_4.jpg', NULL, 'cheap_appliances', 40),
(82, 'Mr. Coffee 12-Cup Coffee Maker', 'Programmable coffee maker with auto pause and serve feature from Mr. Coffee.', 'mrcoffee_coffeemaker_1.png', 'mrcoffee_coffeemaker_2.jpg', 'mrcoffee_coffeemaker_3.jpg', 'mrcoffee_coffeemaker_4.jpg', 'mrcoffee_coffeemaker_5.jpg', 'cheap_appliances', 25),
(83, 'Bissell Featherweight Stick Lightweight Bagless Vacuum', 'Lightweight bagless vacuum cleaner for quick clean-ups from Bissell.', 'bissell_featherweight_vacuum_1.png', 'bissell_featherweight_vacuum_2.jpg', 'bissell_featherweight_vacuum_3.jpg', 'bissell_featherweight_vacuum_4.jpg', 'bissell_featherweight_vacuum_5.jpg', 'cheap_appliances', 30),
(84, 'Hamilton Beach Electric Kettle', 'Stainless steel electric kettle with rapid-boil technology from Hamilton Beach.', 'hamiltonbeach_electrickettle_6.png', 'hamiltonbeach_electrickettle_7.jpg', 'hamiltonbeach_electrickettle_8.jpg', 'hamiltonbeach_electrickettle_9.jpg', 'hamiltonbeach_electrickettle_10.jpg', 'cheap_appliances', 20),
(85, 'Compact Refrigerator', 'Compact refrigerator with adjustable thermostat and reversible door from RCA.', 'rca_compactrefrigerator_1.png', 'rca_compactrefrigerator_2.jpg', 'rca_compactrefrigerator_3.jpg', 'rca_compactrefrigerator_4.jpg', 'rca_compactrefrigerator_5.jpg', 'cheap_appliances', 160),
(86, 'Coleman Sundome 4-Person Tent', 'Easy setup dome tent with WeatherTec system for outdoor camping from Coleman.', 'coleman_sundome_tent_6.png', 'coleman_sundome_tent_2.jpg', 'coleman_sundome_tent_3.jpg', 'coleman_sundome_tent_4.jpg', 'coleman_sundome_tent_5.jpg', 'cheap_sports', 65),
(87, 'Hydro Flask Standard Mouth Water Bottle', 'Vacuum insulated stainless steel water bottle with standard mouth opening from Hydro Flask.', 'hydroflask_waterbottle_1.png', 'hydroflask_waterbottle_2.jpg', 'hydroflask_waterbottle_3.jpg', 'hydroflask_waterbottle_4.jpg', 'hydroflask_waterbottle_5.jpg', 'cheap_sports', 30),
(88, 'Gonex 35L Lightweight Packable Backpack', 'Lightweight foldable backpack with water-resistant nylon fabric from Gonex.', 'gonex_packable_backpack_1.png', NULL, '', NULL, NULL, 'cheap_sports', 20),
(89, 'Igloo 60-Quart Ice Cube Roller Cooler', 'Rolling cooler with push-button telescoping handle and molded side handles from Igloo.', 'igloo_icecube_cooler_1.png', 'igloo_icecube_cooler_2.jpg', 'igloo_icecube_cooler_3.jpg', 'igloo_icecube_cooler_4.jpg', 'igloo_icecube_cooler_5.jpg', 'cheap_sports', 40),
(90, 'Wilson Soccorball', 'Junior size soccorball with soft composite leather cover from Wilson.', 'wilson_nfl_mvp_football_1.png', NULL, NULL, NULL, NULL, 'cheap_sports', 15),
(91, 'SanDisk 128GB Ultra Dual Drive USB Type-C', 'Dual USB Type-C and USB Type-A flash drive with high-speed transfer from SanDisk.', 'sandisk_ultra_dualdrive_1.png', 'sandisk_ultra_dualdrive_2.jpg', 'sandisk_ultra_dualdrive_3.jpg', 'sandisk_ultra_dualdrive_4.jpg', 'sandisk_ultra_dualdrive_5.jpg', 'cheap_electronics', 20),
(92, 'Logitech C270 Desktop or Laptop Webcam', 'HD 720p webcam with noise-reducing microphone for video calls and streaming from Logitech.', 'logitech_c270_webcam_1.png', 'logitech_c270_webcam_2.jpg', 'logitech_c270_webcam_3.jpg', '', '', 'cheap_electronics', 25),
(93, 'TP-Link N300 WiFi Range Extender', 'WiFi range extender with external antennas for better coverage and signal strength from TP-Link.', 'tplink_n300_extender_1.png', 'tplink_n300_extender_2.jpg', 'tplink_n300_extender_3.jpg', 'tplink_n300_extender_4.jpg', 'tplink_n300_extender_5.jpg', 'cheap_electronics', 20),
(94, 'Energizer Max AA Batteries (24 Pack)', 'Long-lasting AA alkaline batteries for household devices from Energizer.', 'energizer_aa_batteries_1.png', 'energizer_aa_batteries_2.jpg', 'energizer_aa_batteries_3.jpg', 'energizer_aa_batteries_4.jpg', 'energizer_aa_batteries_5.jpg', 'cheap_electronics', 14),
(95, 'Anker Power Strip with USB PowerExtend Strip 2 Mini', 'Compact power strip with 2 AC outlets and 2 USB ports from Anker.', 'anker_power_strip_1.png', 'anker_power_strip_2.jpg', 'anker_power_strip_3.jpg', 'anker_power_strip_4.jpg', 'anker_power_strip_5.jpg', 'cheap_electronics', 16),
(96, 'Maybelline New York Great Lash Mascara', 'Iconic mascara for thicker and longer lashes from Maybelline New York.', 'maybelline_greatlash_mascara_6.png', 'maybelline_greatlash_mascara_2.jpg', 'maybelline_greatlash_mascara_3.jpg', 'maybelline_greatlash_mascara_4.jpg', 'maybelline_greatlash_mascara_5.jpg', 'cheap_beauty', 5),
(97, 'Neutrogena Makeup Remover Cleansing Towelettes', 'Pre-moistened makeup remover wipes to effectively dissolve makeup from Neutrogena.', 'neutrogena_makeupremover_towelettes_1.png', 'neutrogena_makeupremover_towelettes_2.jpg', 'neutrogena_makeupremover_towelettes_3.jpg', 'neutrogena_makeupremover_towelettes_4.jpg', NULL, 'cheap_beauty', 7),
(98, 'Visible White toothpaste', 'Professional-grade teeth whitening strips with enamel-safe ingredients from Crest.', 'visible_whitestrips_1.png', NULL, NULL, NULL, NULL, 'cheap_beauty', 48),
(99, 'Revlon Super Lustrous Lipstick', 'Iconic lipstick with creamy formula and high-impact colors from Revlon.', 'revlon_superlustrous_lipstick_1.png', 'revlon_superlustrous_lipstick_2.jpg', 'revlon_superlustrous_lipstick_3.jpg', 'revlon_superlustrous_lipstick_4.jpg', 'revlon_superlustrous_lipstick_5.jpg', 'cheap_beauty', 5),
(100, 'Olay Fresh Outlast Cooling White Strawberry & Mint Body Wash', 'Body wash with long-lasting cooling sensation and strawberry-mint scent from Olay.', 'olay_freshoutlast_bodywash_1.png', 'olay_freshoutlast_bodywash_2.jpg', 'olay_freshoutlast_bodywash_3.jpg', 'olay_freshoutlast_bodywash_4.jpg', NULL, 'cheap_beauty', 4),
(101, 'Educated: A Memoir by Tara Westover', 'Memoir about overcoming adversity through education and self-discovery by Tara Westover.', 'educated_tarawestover_book_3.jpg', NULL, '', '', '', 'cheap_books', 10),
(102, 'Where the Crawdads Sing by Delia Owens', 'Novel set in the marshes of North Carolina about a young woman\'s survival and resilience by Delia Owens.', 'where_crawdads_sing_book_1.jpg', NULL, '', '', '', 'cheap_books', 12),
(103, 'The Silent Patient by Alex Michaelides', 'Psychological thriller about a woman\'s shocking act of violence and the therapist determined to unravel her mystery by Alex Michaelides.', 'silent_patient_alex_michaelides_book_1.jpg', '', '', '', '', 'cheap_books', 12),
(104, 'Little Fires Everywhere by Celeste Ng', 'Novel exploring family dynamics and secrets that upend a quiet suburb by Celeste Ng.', 'little_fires_everywhere_book_1.jpg', NULL, '', '', '', 'cheap_books', 10),
(105, 'The Night Circus by Erin Morgenstern', 'Fantasy novel about a magical competition between two young illusionists by Erin Morgenstern.', 'night_circus_erin_morgenstern_book_1.jpg', NULL, '', '', '', 'cheap_books', 11),
(106, 'Men\'s Ecosmart Fleece Sweatshirt', 'Crewneck fleece sweatshirt made with up to 5% recycled polyester from Hanes.', 'hanes_ecosmart_sweatshirt_1.png', 'hanes_ecosmart_sweatshirt_2.jpg', 'hanes_ecosmart_sweatshirt_3.jpg', 'hanes_ecosmart_sweatshirt_4.jpg', NULL, 'cheap_fashion', 10),
(107, 'Wrangler Authentics Men\'s Classic 5-Pocket Regular Fit Jeans', 'Classic 5-pocket regular fit jeans with stretch denim from Wrangler Authentics.', 'wrangler_authentics_jeans_6.png', 'wrangler_authentics_jeans_7.jpg', 'wrangler_authentics_jeans_8.jpg', 'wrangler_authentics_jeans_9.jpg', 'wrangler_authentics_jeans_10.jpg', 'cheap_fashion', 22),
(108, 'Women\'s Powerblend Graphic Hoodie', 'Soft cotton-blend hoodie with classic graphics.', 'champion_powerblend_hoodie_1.png', 'champion_powerblend_hoodie_2.jpg', 'champion_powerblend_hoodie_3.jpg', 'champion_powerblend_hoodie_4.jpg', 'champion_powerblend_hoodie_5.jpg', 'cheap_fashion', 25),
(109, 'Levi\'s Men\'s 505 Regular Fit Jeans', 'Iconic straight-leg jeans with classic five-pocket styling from Levi\'s.', 'levis_505_jeans_6.png', 'levis_505_jeans_2.jpg', 'levis_505_jeans_3.jpg', 'levis_505_jeans_4.jpg', 'levis_505_jeans_5.jpg', 'cheap_fashion', 30),
(110, 'Adidas Originals Men\'s Stan Smith Sneakers', 'Iconic low-top sneakers with leather upper and perforated 3-Stripes from Adidas Originals.', 'adidas_stan_smith_sneakers_1.png', 'adidas_stan_smith_sneakers_2.jpg', 'adidas_stan_smith_sneakers_3.jpg', 'adidas_stan_smith_sneakers_4.jpg', 'adidas_stan_smith_sneakers_5.jpg', 'cheap_fashion', 60),
(111, 'Microwave with Echo Dot (3rd Gen)', 'Compact microwave oven with Alexa voice control and Echo Dot included from AmazonBasics.', 'amazonbasics_microwave_echo_dot_1.png', 'amazonbasics_microwave_echo_dot_2.jpg', 'amazonbasics_microwave_echo_dot_3.jpg', 'amazonbasics_microwave_echo_dot_4.jpg', 'amazonbasics_microwave_echo_dot_5.jpg', 'cheap_appliances', 65),
(112, 'BLACK+DECKER 4-Slice Toaster Oven', '4-slice toaster oven with bake, broil, toast, and keep warm functions from BLACK+DECKER.', 'blackdecker_toasteroven_6.png', 'blackdecker_toasteroven_7.jpg', 'blackdecker_toasteroven_8.jpg', NULL, NULL, 'cheap_appliances', 30),
(113, 'Eureka Blaze 3-in-1 Swivel Lightweight Stick Vacuum Cleaner', 'Swivel stick vacuum cleaner for hardwood floors and carpets from Eureka.', 'eureka_blaze_vacuum_1.png', 'eureka_blaze_vacuum_2.jpg', 'eureka_blaze_vacuum_3.jpg', 'eureka_blaze_vacuum_4.jpg', 'eureka_blaze_vacuum_5.jpg', 'cheap_appliances', 34),
(114, 'Hamilton Beach Personal Blender', 'Compact blender for smoothies and shakes with 14 oz blending jar from Hamilton Beach.', 'hamiltonbeach_personalblender_6.png', 'hamiltonbeach_personalblender_7.jpg', 'hamiltonbeach_personalblender_8.jpg', 'hamiltonbeach_personalblender_9.jpg', 'hamiltonbeach_personalblender_10.jpg', 'cheap_appliances', 17),
(115, 'Mid-size Anti-Drip Non-Stick Iron', 'Non-stick iron with adjustable temperature and anti-drip system from Sunbeam.', 'sunbeam_nonstick_iron_1.png', 'sunbeam_nonstick_iron_2.jpg', 'sunbeam_nonstick_iron_3.jpg', 'sunbeam_nonstick_iron_4.jpg', 'sunbeam_nonstick_iron_5.jpg', 'cheap_appliances', 25),
(116, 'Spalding NBA Street Basketball', 'Outdoor basketball with durable rubber cover and deep channels from Spalding.', 'spalding_nba_street_basketball_1.png', 'spalding_nba_street_basketball_2.jpg', NULL, '', NULL, 'cheap_sports', 15),
(117, 'Champion Sports Official Tournament and Olympic Sized Volleyball Net', 'Official size volleyball net suitable for tournaments and Olympic play from Champion Sports.', 'champion_sports_volleyballnet_1.png', '', '', '', '', 'cheap_sports', 40),
(118, 'Wilson Tour Slam Lite Tennis Racket', 'Lightweight tennis racket with power strings and comfortable grip from Wilson.', 'wilson_tour_slam_tennisracket_1.jpg', 'wilson_tour_slam_tennisracket_2.jpg', NULL, '', NULL, 'cheap_sports', 28),
(119, 'Bottle Cooler', 'Soft-sided cooler with adjustable shoulder strap and multiple pockets.', 'softcooler_1.png', 'softcooler_2.jpg', NULL, NULL, NULL, 'cheap_sports', 20),
(120, 'Master Lock 8143D Combination Bike Lock', 'Combination bike lock with 4-digit resettable combination from Master Lock.', 'masterlock_bikelock_1.png', 'masterlock_bikelock_2.jpg', 'masterlock_bikelock_3.jpg', 'masterlock_bikelock_4.jpg', 'masterlock_bikelock_5.jpg', 'cheap_sports', 7),
(121, 'Samsung 32-Inch 1080p Smart LED TV', '32-inch Full HD Smart LED TV with built-in Wi-Fi and streaming apps from Samsung.', 'samsung_smarttv_1.png', 'samsung_smarttv_2.jpg', 'samsung_smarttv_3.jpg', 'samsung_smarttv_4.jpg', NULL, 'hour_electronics', 250),
(122, 'Sony Noise Cancelling Headphones WHCH710N', 'Wireless over-ear headphones with active noise cancellation and up to 35 hours of battery life from Sony.', 'sony_headphones_1.png', 'sony_headphones_2.jpg', 'sony_headphones_3.jpg', 'sony_headphones_4.jpg', 'sony_headphones_5.jpg', 'hour_electronics', 148),
(123, 'Apple iPad 10.2-Inch Wi-Fi 64GB', '10.2-inch Retina display iPad with A12 Bionic chip, Touch ID, and support for Apple Pencil and Smart Keyboard.', 'apple_ipad_1.png', 'apple_ipad_2.jpg', 'apple_ipad_3.jpg', 'apple_ipad_4.jpg', 'apple_ipad_5.jpg', 'hour_electronics', 329),
(124, 'Instant Pot Duo 7-in-1 Electric Pressure Cooker', '7-in-1 programmable pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker, and warmer from Instant Pot.', 'instantpot_1.png', 'instantpot_2.jpg', 'instantpot_3.jpg', 'instantpot_4.jpg', 'instantpot_5.jpg', 'hour_appliances', 79),
(125, 'Ninja Professional 72 Oz Countertop Blender', '1000-watt professional blender with 72 oz Total Crushing pitcher for smoothies, ice crushing, and blending from Ninja.', 'ninja_blender_1.png', 'ninja_blender_2.jpg', 'ninja_blender_3.jpg', 'ninja_blender_4.jpg', 'ninja_blender_5.jpg', 'hour_appliances', 90),
(126, 'Echo Dot (4th Gen) with Clock', 'Smart speaker with LED display and Alexa, perfect for bedside or desk use from Amazon.', 'echo_dot_clock_1.png', 'echo_dot_clock_2.jpg', 'echo_dot_clock_3.jpg', 'echo_dot_clock_4.jpg', 'echo_dot_clock_5.jpg', 'hour_electronics', 60),
(127, 'Fitbit Charge 4 Fitness and Activity Tracker', 'Advanced fitness tracker with built-in GPS, heart rate monitoring, and sleep tracking from Fitbit.', 'fitbit_charge4_1.png', 'fitbit_charge4_2.jpg', 'fitbit_charge4_3.jpg', 'fitbit_charge4_4.jpg', 'fitbit_charge4_5.jpg', 'hour_electronics', 130),
(128, 'Cordless Stick Vacuum Cleaner', 'Cordless stick vacuum cleaner with powerful suction and up to 30 minutes of fade-free cleaning from Dyson.', 'dyson_v7_1.png', 'dyson_v7_2.jpg', 'dyson_v7_3.jpg', 'dyson_v7_4.jpg', 'dyson_v7_5.jpg', 'hour_appliances', 250),
(129, 'Fujifilm Instax Mini 11 Instant Camera', 'Compact instant camera with automatic exposure and selfie mode from Fujifilm.', 'fujifilm_instax_1.png', 'fujifilm_instax_2.jpg', 'fujifilm_instax_3.jpg', 'fujifilm_instax_4.jpg', 'fujifilm_instax_5.jpg', 'hour_electronics', 69),
(130, 'Bose SoundLink Color Bluetooth Speaker II', 'Wireless Bluetooth speaker with bold sound and water-resistant design from Bose.', 'bose_soundlink_1.png', 'bose_soundlink_2.jpg', 'bose_soundlink_3.jpg', 'bose_soundlink_4.jpg', 'bose_soundlink_5.jpg', 'hour_electronics', 129),
(131, 'Samsonite Winfield 3 DLX Hardside Luggage', 'Lightweight and durable hardside spinner luggage with TSA lock from Samsonite.', 'samsonite_luggage_1.png', 'samsonite_luggage_2.jpg', 'samsonite_luggage_3.jpg', 'samsonite_luggage_4.jpg', 'samsonite_luggage_5.jpg', 'hour_travel', 130),
(132, 'Keurig K-Classic Coffee Maker', 'Single-serve K-Cup pod coffee maker with 6 to 10 oz brew sizes from Keurig.', 'keurig_kclassic_1.png', 'keurig_kclassic_2.jpg', 'keurig_kclassic_3.jpg', 'keurig_kclassic_4.jpg', 'keurig_kclassic_5.jpg', 'hour_appliances', 80),
(133, 'Apple Watch Series 6 (GPS, 40mm)', 'GPS model with Always-On Retina display, blood oxygen app, and ECG app from Apple.', 'apple_watch_series6_1.png', 'apple_watch_series6_2.jpg', 'apple_watch_series6_3.jpg', 'apple_watch_series6_4.jpg', 'apple_watch_series6_5.jpg', 'hour_electronics', 349),
(134, 'Electric Pressure Washer', 'Electric pressure washer with 5 Quick-Connect spray tips and dual detergent tanks from Sun Joe.', 'sunjoe_pressurewasher_1.png', 'sunjoe_pressurewasher_2.jpg', 'sunjoe_pressurewasher_3.jpg', NULL, NULL, 'hour_tools', 159),
(135, 'Garmin vívofit 4 Activity Tracker', 'Activity tracker with 1+ year battery life and color display from Garmin.', 'garmin_vivofit4_1.png', 'garmin_vivofit4_2.jpg', 'garmin_vivofit4_3.jpg', 'garmin_vivofit4_4.jpg', 'garmin_vivofit4_5.jpg', 'hour_electronics', 60),
(136, 'Ring Video Doorbell Pro', 'Wired video doorbell with advanced motion detection and customizable privacy settings from Ring.', 'ring_doorbell_pro_1.png', 'ring_doorbell_pro_2.jpg', 'ring_doorbell_pro_3.jpg', 'ring_doorbell_pro_4.jpg', 'ring_doorbell_pro_5.jpg', 'hour_electronics', 170),
(137, 'Oculus Quest 2 Advanced All-In-One Virtual Reality Headset', 'All-in-one VR headset with next-level hardware and immersive experiences from Oculus.', 'oculus_quest2_1.png', 'oculus_quest2_2.jpg', 'oculus_quest2_3.jpg', 'oculus_quest2_4.jpg', NULL, 'hour_electronics', 299),
(138, 'Cuisinart 14-Cup Food Processor', '14-cup large capacity food processor with stainless steel blades and discs from Cuisinart.', 'cuisinart_foodprocessor_1.png', 'cuisinart_foodprocessor_2.jpg', NULL, NULL, NULL, 'hour_appliances', 200),
(139, 'JBL Flip 5 Waterproof Portable Bluetooth Speaker', 'Portable Bluetooth speaker with bold sound and waterproof design from JBL.', 'jbl_flip5_1.png', 'jbl_flip5_2.jpg', 'jbl_flip5_3.jpg', 'jbl_flip5_4.jpg', 'jbl_flip5_5.jpg', 'hour_electronics', 120),
(140, 'iRobot Roomba 675 Robot Vacuum', 'Wi-Fi connected robot vacuum with dirt detect sensors and 3-stage cleaning system from iRobot.', 'irobot_roomba_675_1.png', 'irobot_roomba_675_2.jpg', 'irobot_roomba_675_3.jpg', 'irobot_roomba_675_4.jpg', 'irobot_roomba_675_5.jpg', 'hour_appliances', 250),
(141, 'GoPro HERO12 Black - Waterproof Action Camera', 'Waterproof action camera with front LCD and 5K Ultra HD video from GoPro.', 'gopro_hero9_1.png', 'gopro_hero9_2.jpg', 'gopro_hero9_3.jpg', 'gopro_hero9_4.jpg', 'gopro_hero9_5.jpg', 'hour_electronics', 350),
(142, 'Nespresso VertuoPlus Coffee and Espresso Maker', 'Coffee and espresso maker with single-serve coffee and espresso machine from Nespresso.', 'nespresso_vertuoplus_1.png', 'nespresso_vertuoplus_2.jpg', 'nespresso_vertuoplus_3.jpg', 'nespresso_vertuoplus_4.jpg', 'nespresso_vertuoplus_5.jpg', 'hour_appliances', 179),
(143, 'Fitbit Versa 4 Health & Fitness Smartwatch', 'GPS smartwatch with heart rate monitoring, built-in GPS, and voice assistant from Fitbit.', 'fitbit_versa3_1.png', 'fitbit_versa3_2.jpg', 'fitbit_versa3_3.jpg', 'fitbit_versa3_4.jpg', 'fitbit_versa3_5.jpg', 'hour_electronics', 200),
(144, 'Anker Soundcore Liberty Air 4 True Wireless Earbuds', 'True wireless earbuds with active noise cancellation and HearID personalized sound from Anker Soundcore.', 'anker_libertyair2pro_1.png', 'anker_libertyair2pro_2.jpg', 'anker_libertyair2pro_3.jpg', 'anker_libertyair2pro_4.jpg', 'anker_libertyair2pro_5.jpg', 'hour_electronics', 130),
(145, 'Crock-Pot 7-Quart Oval Manual Slow Cooker', '7-quart oval manual slow cooker with high, low, and warm settings from Crock-Pot.', 'crockpot_slowcooker_1.png', NULL, NULL, NULL, NULL, 'hour_appliances', 30),
(146, 'SAMSUNG Galaxy Tab A 8.0-inch 32GB', '8.0-inch lightweight tablet with long battery life and expandable storage from SAMSUNG.', 'samsung_galaxytaba_1.png', 'samsung_galaxytaba_2.jpg', 'samsung_galaxytaba_3.jpg', 'samsung_galaxytaba_4.jpg', 'samsung_galaxytaba_5.jpg', 'hour_electronics', 120),
(147, 'Hamilton Beach FlexBrew Trio Coffee Maker', '3-in-1 coffee maker with single-serve, full-pot, and espresso options from Hamilton Beach.', 'hamiltonbeach_flexbrew_1.png', 'hamiltonbeach_flexbrew_2.jpg', 'hamiltonbeach_flexbrew_3.jpg', 'hamiltonbeach_flexbrew_4.jpg', 'hamiltonbeach_flexbrew_5.jpg', 'hour_appliances', 110),
(148, 'Apple AirPods Pro', 'Active noise cancellation and transparency mode with customizable fit from Apple.', 'apple_airpodspro_1.png', 'apple_airpodspro_2.jpg', 'apple_airpodspro_3.jpg', 'apple_airpodspro_4.jpg', 'apple_airpodspro_5.jpg', 'hour_electronics', 249),
(149, 'Personal Blender', 'Personal blender for shakes and smoothies with 600 watts of power from NutriBullet.', 'nutribullet_blender_1.png', 'nutribullet_blender_2.jpg', 'nutribullet_blender_3.jpg', 'nutribullet_blender_4.jpg', 'nutribullet_blender_5.jpg', 'hour_appliances', 60),
(150, 'Sony PlayStation 5 Console', 'Next-gen console with ultra-high-speed SSD, ray tracing, and 3D audio from Sony PlayStation.', 'sony_ps5_1.png', 'sony_ps5_2.jpg', 'sony_ps5_3.jpg', 'sony_ps5_4.jpg', NULL, 'hour_electronics', 500),
(151, 'Cuisinart Chefs Classic Nonstick Hard-Anodized Cookware Set', 'Hard-anodized cookware set with quantanium nonstick interior from Cuisinart.', 'cuisinart_cookwareset_1.png', NULL, NULL, NULL, NULL, 'hour_appliances', 200),
(152, 'Nintendo Switch Console', 'Hybrid gaming console with detachable Joy-Con controllers and docking station from Nintendo.', 'nintendo_switch_1.png', 'nintendo_switch_2.jpg', 'nintendo_switch_3.jpg', 'nintendo_switch_4.jpg', 'nintendo_switch_5.jpg', 'hour_electronics', 300),
(153, 'Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum', 'Lift-Away upright vacuum with anti-allergen complete seal technology from Shark.', 'shark_navigator_1.png', 'shark_navigator_2.jpg', 'shark_navigator_3.jpg', 'shark_navigator_4.jpg', 'shark_navigator_5.jpg', 'hour_appliances', 150),
(154, 'Canon EOS Rebel T7 DSLR Camera', '24.1 megapixel DSLR camera with EF-S 18-55mm f/3.5-5.6 IS II lens from Canon.', 'canon_eosrebel_t7_1.png', 'canon_eosrebel_t7_2.jpg', 'canon_eosrebel_t7_3.jpg', 'canon_eosrebel_t7_4.jpg', NULL, 'hour_electronics', 449),
(155, 'Hamilton Beach 7-Speed Electric Hand Mixer', 'Electric hand mixer with snap-on storage case and 6 speed options from Hamilton Beach.', 'hamiltonbeach_handmixer_1.png', 'hamiltonbeach_handmixer_2.jpg', 'hamiltonbeach_handmixer_3.jpg', 'hamiltonbeach_handmixer_4.jpg', 'hamiltonbeach_handmixer_5.jpg', 'hour_appliances', 30),
(156, 'Sony 55-Inch 4K Ultra HD Smart LED TV', '55-inch 4K Ultra HD Smart LED TV with HDR and Alexa compatibility from Sony.', 'sony_4ktv_1.png', 'sony_4ktv_2.jpg', 'sony_4ktv_3.jpg', 'sony_4ktv_4.jpg', 'sony_4ktv_5.jpg', 'hour_electronics', 700),
(157, 'Extra Large Digital Countertop Convection Oven', 'Digital countertop convection oven with extra-large capacity from Oster.', 'oster_convectionoven_1.png', 'oster_convectionoven_2.jpg', 'oster_convectionoven_3.jpg', 'oster_convectionoven_4.jpg', NULL, 'hour_appliances', 120),
(158, 'Garmin Forerunner 45 GPS Running Watch', 'GPS running watch with heart rate monitoring and Garmin Coach training plans from Garmin.', 'garmin_forerunner45_1.png', NULL, NULL, '', NULL, 'hour_electronics', 150),
(159, 'Nutri Ninja Personal and Countertop Blender', 'Personal and countertop blender with Auto-iQ technology and 1000 watts of power from Nutri Ninja.', 'nutrininja_blender_1.png', 'nutrininja_blender_2.jpg', 'nutrininja_blender_3.jpg', 'nutrininja_blender_4.jpg', 'nutrininja_blender_5.jpg', 'hour_appliances', 80),
(160, 'Roku Ultra Streaming Media Player', 'Streaming media player with 4K HDR, Dolby Vision, and Dolby Atmos from Roku.', 'roku_ultra_1.png', 'roku_ultra_2.jpg', 'roku_ultra_3.jpg', 'roku_ultra_4.jpg', 'roku_ultra_5.jpg', 'hour_electronics', 100),
(161, 'Bissell Cleanview Swivel Pet Upright Bagless Vacuum Cleaner', 'Upright bagless vacuum cleaner with triple action brush roll and scatter-free technology from Bissell.', 'bissell_cleanview_1.png', 'bissell_cleanview_2.jpg', 'bissell_cleanview_3.jpg', 'bissell_cleanview_4.jpg', 'bissell_cleanview_5.jpg', 'hour_appliances', 100),
(162, 'Fitbit Inspire 2 Health & Fitness Tracker', 'Health and fitness tracker with heart rate monitoring and 10-day battery life from Fitbit.', 'fitbit_inspire2_1.png', 'fitbit_inspire2_2.jpg', 'fitbit_inspire2_3.jpg', 'fitbit_inspire2_4.jpg', 'fitbit_inspire2_5.jpg', 'hour_electronics', 100),
(163, 'KitchenAid Classic Series 4.5 Quart Tilt-Head Stand Mixer', 'Tilt-head stand mixer with 10 speeds and 4.5 quart stainless steel bowl from KitchenAid.', 'kitchenaid_standmixer_1.png', 'kitchenaid_standmixer_2.jpg', 'kitchenaid_standmixer_3.jpg', 'kitchenaid_standmixer_4.jpg', 'kitchenaid_standmixer_5.jpg', 'hour_appliances', 260),
(164, 'Apple MacBook Air (M1, 2020)', '13.3-inch MacBook Air with Apple M1 chip, 8GB RAM, and 256GB SSD storage.', 'macbook_air_m1_1.png', 'macbook_air_m1_2.jpg', 'macbook_air_m1_3.jpg', 'macbook_air_m1_4.jpg', 'macbook_air_m1_5.jpg', 'daily_electronics', 999),
(165, 'Sony A7 III Mirrorless Camera', '24.2 MP full-frame mirrorless camera with 4K video recording and 693-point AF system from Sony.', 'sony_a7iii_1.png', 'sony_a7iii_2.jpg', 'sony_a7iii_3.jpg', 'sony_a7iii_4.jpg', 'sony_a7iii_5.jpg', 'daily_electronics', 1998),
(166, 'Samsung 55-Inch QLED 4K UHD TV', '55-inch QLED 4K UHD Smart TV with Quantum HDR and Alexa compatibility from Samsung.', 'samsung_qledtv_1.png', 'samsung_qledtv_2.jpg', 'samsung_qledtv_3.jpg', 'samsung_qledtv_4.jpg', 'samsung_qledtv_5.jpg', 'daily_electronics', 1300),
(167, 'Star Wars Luke Skywalker Action Figure', 'Vintage Star Wars action figure of Luke Skywalker in original packaging, highly collectible.', 'starwars_luke_1.png', 'starwars_luke_2.jpg', NULL, NULL, NULL, 'daily_collectibles', 300),
(168, 'LG OLED 65-Inch 4K Ultra HD Smart TV', '65-inch OLED 4K Ultra HD Smart TV with Dolby Vision IQ and AI ThinQ from LG Electronics.', 'lg_oledtv_1.png', 'lg_oledtv_2.jpg', 'lg_oledtv_3.jpg', 'lg_oledtv_4.jpg', 'lg_oledtv_5.jpg', 'daily_electronics', 2799),
(169, 'Star Wars Boba Fett Action Figure', 'Vintage Star Wars action figure of Boba Fett in original packaging, highly collectible.', 'starwars_bobafett_1.png', 'starwars_bobafett_2.jpg', 'starwars_bobafett_3.jpg', 'starwars_bobafett_4.jpg', 'starwars_bobafett_5.jpg', 'daily_collectibles', 800),
(170, 'Apple iPhone 15 Pro Max', '6.7-inch Super Retina XDR display iPhone with A17 Pro chip and Ceramic Shield from Apple.', 'iphone_12promax_1.png', 'iphone_12promax_2.jpg', 'iphone_12promax_3.jpg', 'iphone_12promax_4.jpg', 'iphone_12promax_5.jpg', 'daily_electronics', 1099),
(171, 'Sony 85-Inch BRAVIA XR OLED 4K Ultra HD Smart TV', '85-inch BRAVIA XR OLED 4K Ultra HD Smart TV with Cognitive Processor XR from Sony.', 'sony_braviaxr_1.png', 'sony_braviaxr_2.jpg', 'sony_braviaxr_3.jpg', 'sony_braviaxr_4.jpg', NULL, 'daily_electronics', 5000),
(172, 'Marvel Amazing Fantasy #15 (Spider-Man First Appearance)', 'High-grade original Amazing Fantasy #15 comic featuring the first appearance of Spider-Man.', 'spiderman_comic_1.jpg', NULL, NULL, NULL, NULL, 'daily_collectibles', 15000),
(173, 'Apple iMac ', '27-inch iMac with Retina 5K display, 8-core CPU, 8GB RAM, and 256GB SSD storage from Apple.', 'imac_27inch_1.png', 'imac_27inch_2.jpeg', NULL, NULL, NULL, 'daily_electronics', 1799),
(174, 'Sony Alpha  Mirrorless Camera', 'Full-frame mirrorless camera with 20 fps continuous shooting and blackout-free electronic viewfinder from Sony.', 'sony_a9ii_1.png', 'sony_a9ii_2.jpg', 'sony_a9ii_3.jpg', 'sony_a9ii_4.jpg', 'sony_a9ii_5.jpg', 'daily_electronics', 4498),
(175, 'Samsung The Frame 65-Inch QLED 4K UHD Smart TV', '65-inch QLED 4K UHD Smart TV with Art Mode and customizable frame options from Samsung.', 'samsung_theframe_1.png', 'samsung_theframe_2.jpg', 'samsung_theframe_3.jpg', 'samsung_theframe_4.jpg', 'samsung_theframe_5.jpg', 'daily_electronics', 2199),
(176, 'Nintendo Switch OLED with Joy-Con', 'Customers like the quality and functionality of the video game console. They mention it\'s a fantastic console to kill time with classics.\n\n', 'nintendo_championships_1.png', 'nintendo_championships_2.jpg', 'nintendo_championships_3.jpg', 'nintendo_championships_4.jpg', 'nintendo_championships_5.jpg', 'daily_collectibles', 2000),
(177, 'Samsung 75-Inch Neo QLED 8K Smart TV', '75-inch Neo QLED 8K Smart TV with Quantum Matrix Technology and Object Tracking Sound from Samsung.', 'samsung_neoqled_1.png', 'samsung_neoqled_2.jpg', 'samsung_neoqled_3.jpg', 'samsung_neoqled_4.jpg', 'samsung_neoqled_5.jpg', 'daily_electronics', 3999),
(178, 'Star Wars Charizard Base Set 1st Edition', 'Rare 1st Edition holographic Charizard card from the Pokemon TCG Base Set.', 'pokemon_charizard_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 1500),
(179, 'Sony PlayStation 5 Digital Edition', 'Next-gen digital gaming console with ultra-high-speed SSD and immersive 3D audio from Sony PlayStation.', 'playstation5_digital_1.png', 'playstation5_digital_2.png', NULL, NULL, NULL, 'daily_electronics', 400);
INSERT INTO `tbl_items` (`item_id`, `o_name`, `o_desc`, `o_image`, `o_image1`, `o_image2`, `o_image3`, `o_image4`, `item_cat`, `price`) VALUES
(180, 'Vintage Rolex Daytona Chronograph Watch', 'Iconic chronograph watch with self-winding movement and luxurious design from Rolex.', 'rolex_daytona_1.png', 'rolex_daytona_2.jpg', 'rolex_daytona_3.jpg', 'rolex_daytona_4.jpg', 'rolex_daytona_5.jpg', 'daily_collectibles', 30000),
(181, 'Sony PlayStation 4 Pro', '4K HDR gaming console with 1TB storage and enhanced graphics from Sony PlayStation.', 'playstation4_pro_1.png', NULL, NULL, NULL, NULL, 'daily_electronics', 400),
(182, 'Vintage Gibson Les Paul Electric Guitar', 'Classic electric guitar known for its iconic sound and craftsmanship from Gibson.', 'gibson_lespaul_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 6000),
(183, 'Samsung 65-Inch Q70T QLED 4K UHD TV', '65-inch Q70T QLED 4K UHD Smart TV with Quantum HDR and Alexa compatibility from Samsung.', 'samsung_q70t_1.png', 'samsung_q70t_2.jpg', 'samsung_q70t_3.jpg', 'samsung_q70t_4.jpg', 'samsung_q70t_5.jpg', 'daily_electronics', 1500),
(184, 'Vintage Omega Speedmaster Moonwatch', 'Iconic chronograph watch worn during NASA moon missions, highly collectible from Omega.', 'omega_speedmaster_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 15000),
(185, 'Apple iPad Pro 12.9-Inch (2021)', '12.9-inch iPad Pro with Liquid Retina XDR display, Apple M1 chip, and 1TB storage.', 'ipad_pro_12inch_1.png', 'ipad_pro_12inch_2.jpg', 'ipad_pro_12inch_3.jpg', 'ipad_pro_12inch_4.jpg', 'ipad_pro_12inch_5.jpg', 'daily_electronics', 1099),
(186, 'Vintage Coca-Cola Metal Sign', 'Classic Coca-Cola metal advertising sign from the mid-20th century, nostalgic collector\'s item.', 'cocacola_sign_1.png', 'cocacola_sign_2.jpg', 'cocacola_sign_3.jpg', NULL, NULL, 'daily_collectibles', 300),
(187, 'Nintendo Switch OLED Model', 'Improved Nintendo Switch with OLED screen, enhanced audio, and 64GB internal storage.', 'nintendo_switch_oled_1.png', 'nintendo_switch_oled_2.jpg', 'nintendo_switch_oled_3.jpg', 'nintendo_switch_oled_4.jpg', 'nintendo_switch_oled_5.jpg', 'daily_electronics', 350),
(188, 'Vintage Fender Stratocaster Electric Guitar', 'Iconic electric guitar known for its versatile sound and classic design from Fender.', 'fender_stratocaster_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 5000),
(189, 'Sony 65-Inch A90J BRAVIA XR OLED 4K Ultra HD Smart TV', '65-inch A90J BRAVIA XR OLED 4K Ultra HD Smart TV with Cognitive Processor XR from Sony.', 'sony_a90j_1.png', 'sony_a90j_2.jpg', 'sony_a90j_3.jpg', 'sony_a90j_4.jpg', 'sony_a90j_5.jpg', 'daily_electronics', 3300),
(190, 'Vintage Polaroid SX-70 Instant Camera', 'Instant film camera known for its foldable design and classic Polaroid instant photos.', 'polaroid_sx70_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 800),
(191, 'Microsoft Surface Pro 7', '12.3-inch Surface Pro 7 with Intel Core i5, 8GB RAM, and 128GB SSD storage from Microsoft.', 'surface_pro7_1.png', 'surface_pro7_2.jpg', 'surface_pro7_3.jpg', 'surface_pro7_4.jpg', 'surface_pro7_5.jpg', 'daily_electronics', 799),
(192, 'Vintage Schwinn Stingray Bicycle', 'Classic banana-seat bicycle known for its retro design and smooth ride from Schwinn.', 'schwinn_stingray_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 1000),
(193, 'Samsung Galaxy Tab S7+', '12.4-inch Galaxy Tab S7+ with Super AMOLED display, Snapdragon 865+ processor, and S Pen.', 'samsung_tabs7plus_1.png', 'samsung_tabs7plus_2.jpg', 'samsung_tabs7plus_3.jpg', 'samsung_tabs7plus_4.jpg', 'samsung_tabs7plus_5.jpg', 'daily_electronics', 850),
(194, 'Vintage Atari 2600 Console', 'Iconic Atari 2600 console with classic joysticks and cartridges, pioneering video gaming history.', 'atari_2600_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 500),
(195, 'Sony WH-1000XM4 Wireless Noise-Cancelling Headphones', 'Premium wireless noise-cancelling headphones with LDAC and Dual Noise Sensor technology from Sony.', 'sony_wh1000xm4_1.png', 'sony_wh1000xm4_2.jpg', 'sony_wh1000xm4_3.jpg', 'sony_wh1000xm4_4.jpg', 'sony_wh1000xm4_5.jpg', 'daily_electronics', 348),
(196, 'Vintage Hot Wheels Redline Custom Barracuda', 'Rare Redline Hot Wheels Custom Barracuda die-cast car, sought after by collectors.', 'hotwheels_barracuda_1.png', NULL, NULL, NULL, NULL, 'daily_collectibles', 3000),
(197, 'Tesla Model S', 'Electric luxury sedan with autopilot features and premium interior from Tesla.', 'tesla_model_s_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 90000),
(198, 'Apple Watch Series 9', 'Advanced smartwatch with Always-On Retina display and health monitoring features from Apple.', 'apple_watch_series9_1.png', 'apple_watch_series9_2.jpg', 'apple_watch_series9_3.jpg', 'apple_watch_series9_4.jpg', 'apple_watch_series9_5.jpg', 'weekly_electronics', 499),
(199, 'Ferrari 488 GTB', 'Mid-engine sports car with twin-turbo V8 engine and iconic Ferrari design.', 'ferrari_488gtb_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 250000),
(200, 'Canon EOS R5 Mirrorless Camera', '45 MP full-frame mirrorless camera with 8K video recording and advanced autofocus from Canon.', 'canon_eosr5_1.png', 'canon_eosr5_2.jpg', 'canon_eosr5_3.jpg', 'canon_eosr5_4.jpg', 'canon_eosr5_5.jpg', 'weekly_electronics', 3899),
(201, 'Rolex Submariner Date', 'Iconic diving watch with ceramic bezel, waterproof capabilities, and luxury craftsmanship from Rolex.', 'rolex_submariner_1.png', NULL, NULL, NULL, NULL, 'weekly_collectibles', 15000),
(202, 'Sony 85-Inch MASTER Series BRAVIA XR OLED 8K TV', '85-inch MASTER Series BRAVIA XR OLED 8K Smart TV with Acoustic Surface Audio+ from Sony.', 'sony_braviaxr_8k_1.png', NULL, NULL, NULL, NULL, 'weekly_electronics', 9999),
(203, 'Patek Philippe Nautilus', 'Luxury sports watch with self-winding movement, sapphire crystal, and iconic design from Patek Philippe.', 'patek_nautilus_1.png', NULL, NULL, NULL, NULL, 'weekly_collectibles', 80000),
(204, 'Mercedes-Benz G-Class SUV', 'Luxury SUV with robust off-road capabilities and signature Mercedes-Benz design.', 'mercedes_gclass_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 120000),
(205, 'Leica M10-R Digital Rangefinder Camera', 'High-resolution digital rangefinder camera with full-frame CMOS sensor and precise manual focusing from Leica.', 'leica_m10r_1.png', 'leica_m10r_2.jpg', 'leica_m10r_3.jpg', NULL, NULL, 'weekly_electronics', 8995),
(206, '1967 Shelby GT500', 'Classic American muscle car with powerful V8 engine and iconic Shelby performance.', 'shelby_gt500_1.png', 'shelby_gt500_2.jpg', 'shelby_gt500_3.jpg', NULL, NULL, 'weekly_automobiles', 95000),
(207, 'Bang & Olufsen BeoVision Harmony 88-Inch 8K TV', '88-inch 8K OLED TV with motorized speakers and immersive sound from Bang & Olufsen.', 'bangolufsen_harmony_1.png', NULL, NULL, NULL, NULL, 'weekly_electronics', 89999),
(208, 'Lamborghini Huracán EVO', 'Exotic supercar with V10 engine, advanced aerodynamics, and striking Lamborghini design.', 'lamborghini_huracan_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 250000),
(209, 'Panerai Luminor Marina', 'Dive watch with iconic crown protector, luminous markers, and rugged design from Panerai.', 'panerai_luminor_1.png', NULL, NULL, NULL, NULL, 'weekly_collectibles', 10000),
(210, 'BMW M8 Competition', 'High-performance sedan with twin-turbo V8 engine, M xDrive, and luxurious BMW M design.', 'bmw_m5_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 110000),
(211, 'Nikon Z9 Mirrorless Camera', 'High-speed mirrorless camera with 45.7 MP sensor, 8K video recording, and advanced autofocus from Nikon.', 'nikon_z9_1.png', 'nikon_z9_2.jpg', 'nikon_z9_3.jpg', 'nikon_z9_4.jpg', 'nikon_z9_5.jpg', 'weekly_electronics', 5499),
(212, '1970 Chevrolet Chevelle SS 454', 'Classic American muscle car with 454 V8 engine and iconic Chevelle styling.', 'chevrolet_chevelle_ss_1.png', 'chevrolet_chevelle_ss_2.jpg', NULL, NULL, NULL, 'weekly_automobiles', 85000),
(213, 'Breguet Classique Grande Complication Tourbillon', 'Elegant tourbillon watch with intricate complications and timeless craftsmanship from Breguet.', 'breguet_tourbillon_1.png', NULL, NULL, NULL, NULL, 'weekly_collectibles', 90000),
(214, 'Aston Martin DBS Superleggera', 'Grand tourer with twin-turbo V12 engine, aerodynamic design, and luxurious Aston Martin heritage.', 'astonmartin_dbs_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 300000),
(215, 'Leica M11 Digital Rangefinder Camera', 'High-resolution digital rangefinder camera with new 60 MP sensor and advanced shooting capabilities from Leica.', 'leica_m11_1.png', NULL, NULL, NULL, NULL, 'weekly_electronics', 10995),
(216, '1965 Ford Mustang Fastback', 'Classic American pony car with powerful V8 engine and iconic Mustang fastback design.', 'ford_mustang_fastback_1.png', NULL, NULL, NULL, NULL, 'weekly_automobiles', 75000),
(217, 'Men\'s Military Digital Watches', 'Anti-scratch mineral glass and environmental protection vacuum plating case never fade. Genuine leather strap, delicate and soft.', 'men_military_watch_6.png', 'men_military_watch_7.jpg', 'men_military_watch_8.jpg', 'men_military_watch_9.jpg', 'men_military_watch_10.jpg', 'monthly_collectibles', 200000),
(218, 'Bentley Continental GT Speed', 'Grand tourer with twin-turbocharged W12 engine, handcrafted interior, and British luxury from Bentley.', 'bentley_continental_gt_1.png', NULL, NULL, NULL, NULL, 'monthly_automobiles', 300000),
(219, 'Watch for Men Blue Dial', 'Our leather straps watch not only makes a comfortable sense for your wrist but also easy to match your clothes. Our chronograph wrist watches are perfect for the adventurer or the everyday man who is looking for a stylish match to his outfit. ', 'fpjourne_tourbillon_1.png', 'fpjourne_tourbillon_2.jpg', 'fpjourne_tourbillon_3.jpg', 'fpjourne_tourbillon_4.jpg', 'fpjourne_tourbillon_5.jpg', 'monthly_collectibles', 180000),
(220, 'McLaren 765LT', 'High-performance supercar with twin-turbo V8 engine, carbon-fiber construction, and track-focused dynamics from McLaren.', 'mclaren_765lt_1.png', 'mclaren_765lt_2.jpg', 'mclaren_765lt_3.jpg', 'mclaren_765lt_4.jpg', 'mclaren_765lt_5.jpg', 'monthly_automobiles', 350000),
(221, 'Elegant Watch', 'Elegant Watch', 'elegant_watch_1.png', 'elegant_watch_2.jpg', 'elegant_watch_3.jpg', 'elegant_watch_4.jpg', NULL, 'monthly_collectibles', 600000);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_items`
--
ALTER TABLE `tbl_items`
  ADD PRIMARY KEY (`item_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_items`
--
ALTER TABLE `tbl_items`
  MODIFY `item_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=231;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
